import requests

URL_API = "http://localhost:3000/api/product"
TOKEN_ADMIN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MGRiZmQxNmUzM2I0NjAwYTcyZjYwNCJ9.u6LA8aX7-9UVNFX4yDHfRWBluA_tKvL7XqrIy3_XDc4"

headers = {"Authorization": f"Bearer {TOKEN_ADMIN}", "Content-Type": "application/json"}
products = [
    # 10 Laptop
    {
        "title": "Laptop Pro 15″",
        "description": "Laptop high-end untuk profesional, 15 inci, prosesor terbaru.",
        "imageUrl": "https://images.unsplash.com/photo-1555617117-08bce3086172",
        "price": 7000000,
        "productType": "laptop",
        "stock": 10,
    },
    {
        "title": "Laptop Ultrabook 13″",
        "description": "Ringan dan ultra-portabel, cocok untuk mobile developer.",
        "imageUrl": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8",
        "price": 5500000,
        "productType": "laptop",
        "stock": 15,
    },
    {
        "title": "Laptop Gaming 17″",
        "description": "Laptop gaming 17 inci dengan GPU high-end untuk developer yang juga gamer.",
        "imageUrl": "https://images.unsplash.com/photo-1539884537273-7acdcc3d06a9",
        "price": 8000000,
        "productType": "laptop",
        "stock": 5,
    },
    {
        "title": "Laptop Business 14″",
        "description": "Laptop bisnis 14 inci dengan keamanan tambahan dan konektivitas lengkap.",
        "imageUrl": "https://images.unsplash.com/photo-1498050108023-c5249f4df085",
        "price": 6000000,
        "productType": "laptop",
        "stock": 8,
    },
    {
        "title": "Laptop Hybrid 2-in-1 13″",
        "description": "Laptop convertible 2-in-1, layar sentuh dan stylus support.",
        "imageUrl": "https://images.unsplash.com/photo-1498050108023-0f9c1dcf8b11",
        "price": 5200000,
        "productType": "laptop",
        "stock": 12,
    },
    {
        "title": "Laptop Creator 16″",
        "description": "Laptop untuk kreator konten, layar besar 16 inci dengan kalibrasi warna profesional.",
        "imageUrl": "https://images.unsplash.com/photo-1561154464-2a2a1e1d7d94",
        "price": 6500000,
        "productType": "laptop",
        "stock": 7,
    },
    {
        "title": "Laptop Student 15″",
        "description": "Laptop dengan harga terjangkau, cocok untuk pelajar dan mahasiswa.",
        "imageUrl": "https://images.unsplash.com/photo-1517430816045-d1d1fbd2b1d1",
        "price": 5000000,
        "productType": "laptop",
        "stock": 20,
    },
    {
        "title": "Laptop Ultraportable 11″",
        "description": "Laptop super ringan 11 inci, ideal untuk travel dan remote working.",
        "imageUrl": "https://images.unsplash.com/photo-1527430253228-e93688616381",
        "price": 5300000,
        "productType": "laptop",
        "stock": 10,
    },
    {
        "title": "Laptop Workstation 15″",
        "description": "Laptop workstation dengan GPU dan CPU kelas workstation untuk tugas berat.",
        "imageUrl": "https://images.unsplash.com/photo-1586281380397-16c6d1d3d7b3",
        "price": 9000000,
        "productType": "laptop",
        "stock": 4,
    },
    {
        "title": "Laptop Refurbished Certified 15″",
        "description": "Laptop refurbished bersertifikasi dengan garansi, performa tinggi di harga lebih rendah.",
        "imageUrl": "https://images.unsplash.com/photo-1580657013410-1d18d7c8c4a2",
        "price": 5500000,
        "productType": "laptop",
        "stock": 6,
    },
    # 10 Monitor
    {
        "title": "Monitor 27″ QHD",
        "description": "Monitor 27 inci dengan resolusi QHD, ideal untuk multitasking.",
        "imageUrl": "https://images.unsplash.com/photo-1573497491208-6b1acb260507",
        "price": 1500000,
        "productType": "monitor",
        "stock": 14,
    },
    {
        "title": "Monitor UltraWide 34″",
        "description": "Monitor ultra-wide 34 inci untuk pengalaman kerja yang immersive.",
        "imageUrl": "https://images.unsplash.com/photo-1516507246022-80d0277d8179",
        "price": 2500000,
        "productType": "monitor",
        "stock": 9,
    },
    {
        "title": "Monitor 24″ Full HD",
        "description": "Monitor 24 inci Full HD, solusi hemat untuk setup kantor atau home office.",
        "imageUrl": "https://images.unsplash.com/photo-1527430253228-xxx",
        "price": 1100000,
        "productType": "monitor",
        "stock": 18,
    },
    {
        "title": "Monitor Gaming 32″ 144Hz",
        "description": "Monitor gaming 32 inci dengan refresh rate 144Hz dan response rendah.",
        "imageUrl": "https://images.unsplash.com/photo-1586281380397-xxx",
        "price": 3000000,
        "productType": "monitor",
        "stock": 7,
    },
    {
        "title": "Monitor 27″ 4K HDR",
        "description": "Monitor profesional 27 inci dengan resolusi 4K dan dukungan HDR.",
        "imageUrl": "https://images.unsplash.com/photo-1580657013410-xxx",
        "price": 2800000,
        "productType": "monitor",
        "stock": 8,
    },
    {
        "title": "Monitor Curved 34″ QHD",
        "description": "Monitor curved 34 inci dengan resolusi QHD untuk pengalaman sinematik.",
        "imageUrl": "https://images.unsplash.com/photo-1561154464-xxx",
        "price": 2600000,
        "productType": "monitor",
        "stock": 6,
    },
    {
        "title": "Monitor Portable 15.6″ USB-C",
        "description": "Monitor 15.6 inci portable, koneksi USB-C, cocok untuk setup travel.",
        "imageUrl": "https://images.unsplash.com/photo-1517430816045-xxx",
        "price": 1200000,
        "productType": "monitor",
        "stock": 12,
    },
    {
        "title": "Monitor HDMI-KVM 27″",
        "description": "Monitor 27 inci dengan fitur KVM switch untuk banyak komputer.",
        "imageUrl": "https://images.unsplash.com/photo-1527430253228-xxx2",
        "price": 1900000,
        "productType": "monitor",
        "stock": 10,
    },
    {
        "title": "Monitor Budget 22″",
        "description": "Monitor 22 inci budget-friendly untuk kebutuhan dasar.",
        "imageUrl": "https://images.unsplash.com/photo-1586281380397-xxx2",
        "price": 1000000,
        "productType": "monitor",
        "stock": 20,
    },
    {
        "title": "Monitor Professional Color 32″",
        "description": "Monitor 32 inci dengan color gamut tinggi (AdobeRGB), untuk desainer grafis.",
        "imageUrl": "https://images.unsplash.com/photo-1580657013410-xxx2",
        "price": 2900000,
        "productType": "monitor",
        "stock": 5,
    },
    # 10 Meja
    {
        "title": "Meja Kerja Kayu Solid",
        "description": "Meja kerja dari kayu solid dengan desain minimalis untuk home-office.",
        "imageUrl": "https://images.unsplash.com/photo-1570129477492-45c003edd2be",
        "price": 800000,
        "productType": "meja",
        "stock": 10,
    },
    {
        "title": "Meja Standing Adjustable",
        "description": "Meja standing adjustable untuk berdiri dan duduk bergantian.",
        "imageUrl": "https://images.unsplash.com/photo-1581276879432-15a5d8a39a7b",
        "price": 1500000,
        "productType": "meja",
        "stock": 5,
    },
    {
        "title": "Meja Minimalis Putih",
        "description": "Meja dengan desain minimalis warna putih, cocok untuk interior modern.",
        "imageUrl": "https://images.unsplash.com/photo-1519710164239-da123dc03ef4",
        "price": 650000,
        "productType": "meja",
        "stock": 12,
    },
    {
        "title": "Meja Komputer L Shape",
        "description": "Meja komputer berbentuk L untuk memaksimalkan ruang pojok.",
        "imageUrl": "https://images.unsplash.com/photo-1598300055003-cd8caab7a8af",
        "price": 1400000,
        "productType": "meja",
        "stock": 6,
    },
    {
        "title": "Meja Industri Besi & Kayu",
        "description": "Meja dengan kombinasi rangka besi dan alas kayu, gaya industrial.",
        "imageUrl": "https://images.unsplash.com/photo-1481277542470-xxx",
        "price": 900000,
        "productType": "meja",
        "stock": 7,
    },
    {
        "title": "Meja Lipat Portable",
        "description": "Meja lipat portable untuk membuat setup fleksibel di ruang kecil.",
        "imageUrl": "https://images.unsplash.com/photo-1498050108023-xxx",
        "price": 550000,
        "productType": "meja",
        "stock": 15,
    },
    {
        "title": "Meja Gaming RGB",
        "description": "Meja gaming dengan fitur RGB lighting dan penataan kabel terintegrasi.",
        "imageUrl": "https://images.unsplash.com/photo-1527430253228-xxx2",
        "price": 1200000,
        "productType": "meja",
        "stock": 4,
    },
    {
        "title": "Meja Kantor Ergonomis",
        "description": "Meja kantor ergonomis dengan pengaturan ketinggian dan manajemen kabel.",
        "imageUrl": "https://images.unsplash.com/photo-1586281380397-xxx2",
        "price": 850000,
        "productType": "meja",
        "stock": 9,
    },
    {
        "title": "Meja Belajar Anak",
        "description": "Meja belajar dengan desain ramah anak dan ruang penyimpanan tambahan.",
        "imageUrl": "https://images.unsplash.com/photo-1580657013410-xxx2",
        "price": 600000,
        "productType": "meja",
        "stock": 13,
    },
    {
        "title": "Meja Tambahan untuk Laptop",
        "description": "Meja kecil tambahan khusus untuk laptop, ideal untuk ruang tamu atau kamar.",
        "imageUrl": "https://images.unsplash.com/photo-1561154464-xxx2",
        "price": 500000,
        "productType": "meja",
        "stock": 20,
    },
    # 10 Kursi
    {
        "title": "Kursi Ergonomis Premium",
        "description": "Kursi ergonomis dengan sandaran kepala dan dukungan lumbar.",
        "imageUrl": "https://images.unsplash.com/photo-1586105251261-72a756497a01",
        "price": 1000000,
        "productType": "kursi",
        "stock": 8,
    },
    {
        "title": "Kursi Gaming RGB",
        "description": "Kursi gaming dengan aksen RGB dan sandaran yang bisa dibaringkan.",
        "imageUrl": "https://images.unsplash.com/photo-1598300055003-cd8caab7a8af",
        "price": 700000,
        "productType": "kursi",
        "stock": 12,
    },
    {
        "title": "Kursi Kantor Minimalis",
        "description": "Kursi kantor dengan desain minimalis dan bantalan nyaman.",
        "imageUrl": "https://images.unsplash.com/photo-1519710164239-da123dc03ef4",
        "price": 550000,
        "productType": "kursi",
        "stock": 15,
    },
    {
        "title": "Kursi Putar Swivel High-Back",
        "description": "Kursi dengan fitur swivel dan high-back untuk kenyamanan jangka panjang.",
        "imageUrl": "https://images.unsplash.com/photo-1481277542470-xxx",
        "price": 650000,
        "productType": "kursi",
        "stock": 6,
    },
    {
        "title": "Kursi Belajar Anak",
        "description": "Kursi belajar ukuran anak dengan sandaran ergonomis dan warna cerah.",
        "imageUrl": "https://images.unsplash.com/photo-1498050108023-xxx",
        "price": 500000,
        "productType": "kursi",
        "stock": 20,
    },
    {
        "title": "Kursi Lipat Portable",
        "description": "Kursi lipat yang mudah disimpan, ideal untuk ruang tamu ataupun ekstra bangku.",
        "imageUrl": "https://images.unsplash.com/photo-1527430253228-xxx2",
        "price": 520000,
        "productType": "kursi",
        "stock": 18,
    },
    {
        "title": "Kursi Kulit Executive",
        "description": "Kursi kulit untuk eksekutif, desain elegan dan nyaman.",
        "imageUrl": "https://images.unsplash.com/photo-1586281380397-xxx2",
        "price": 1200000,
        "productType": "kursi",
        "stock": 4,
    },
    {
        "title": "Kursi Gaming Bucket Seat",
        "description": "Kursi gaming bucket seat dengan rangka logam dan bantal tambahan.",
        "imageUrl": "https://images.unsplash.com/photo-1580657013410-xxx2",
        "price": 800000,
        "productType": "kursi",
        "stock": 7,
    },
    {
        "title": "Kursi Kantor Mesh",
        "description": "Kursi kantor dengan sandaran jaring (mesh) dan bantalan udara.",
        "imageUrl": "https://images.unsplash.com/photo-1561154464-xxx2",
        "price": 650000,
        "productType": "kursi",
        "stock": 10,
    },
    {
        "title": "Kursi Outdoor Teras",
        "description": "Kursi outdoor yang bisa juga digunakan sebagai kursi kerja casual di balkon/teras.",
        "imageUrl": "https://images.unsplash.com/photo-1517430816045-xxx2",
        "price": 500000,
        "productType": "kursi",
        "stock": 14,
    },
]

for product in products:
    response = requests.post(URL_API, headers=headers, json=product)
    print(f"Sent product \"{product['title']}\" => status {response.status_code}")
    try:
        print("Response:", response.json())
    except:
        print("No JSON response body.")
